# Generated by Django 4.1.3 on 2022-12-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('trade_code', models.CharField(max_length=100, null=True)),
                ('high', models.FloatField(null=True)),
                ('low', models.FloatField(null=True)),
                ('open', models.FloatField(null=True)),
                ('close', models.FloatField(null=True)),
                ('volume', models.IntegerField(null=True)),
            ],
        ),
    ]
